apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: myapp
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'

